[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
github-cli = "latest"
jj = "latest"
kubectl = "latest"
terragrunt = "latest"
usage = "latest"
uv = "latest"
jjui = "latest"
atuin = "latest"
rust = "latest"
claude-code = "latest"
k9s = "latest"
"github:busser/tfautomv" = "latest"
"pipx:llm" = "latest"
gcloud = "latest"
go = "latest"
pipx = "latest"
terraform = "1.10"
vault = "latest"
node = "22"
yq = "latest"
